### ISSUE TITLE
Carousel image as background, a good idea ?

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes_gridelements#19]
Hi,
Carousel image as style background do have at least 2 main disadvantages over images.

* Height of container has to be set.
* In order to handle mediaqueries, you should have a &lt;style&gt; tag

As they are often in homepages, having a 1920 px image may cause huge negative impact over page loading on mobile devices. So a real mediaquery handling is necessary.

**Comment by Bunnyfield** [comment]
Please discuss that with the people who are creating the themes we are currently porting to TYPO3 THEMES. 90% of the themes on wrapbootstrap are using background images, so this is what we have to provide.

Of course we can think about other ways and improvements, but after all it's neither our idea nor our decision.

<style>-Tag should be no big deal, since we are handling the stuff with innerWrap anyway. So we could create a tag inside the DIV instead of an additional attribute. Still we must handle those images with the default CSS provided by the theme, which is why <img> does not work without a lot of modifications to the original CSS.

Opinions?

**Comment by Bunnyfield** [comment]
style tag has been implemented
