### ISSUE TITLE
Iterate over view children by id with viewhelper lead to loosing registers in childrens.

### ISSUE THREAD

**Issue by s-leger** [typo3-themes/themes_gridelements#21]
Iterate over view children by id with viewhelper lead to loosing registers in childrens.

Using typoscript allow Iterating over a view_children without loosing registers.

```
 <f:for each="{data.tx_gridelements_view_children}" as="item" iteration="iteration">
    <div class="item {f:if(condition:'{iteration.isFirst}',then:' active')}" data-itemno="{iteration.index}"> 
      <f:cObject typoscriptObjectPath="tt_content" data="{item}" /> 
    </div>
  </f:for>
```

**Comment by Bunnyfield** [comment]
You are not "losing" registers - fluid is just working with a completely different scope. So iterating over children by ID will just give you prerendered HTML data of each child, which might be enough for most of the scenarios, since children are not rendered via fluid anyway.

So the HTML is generated first and then transferred to fluid as an array. If you want to use registers there, you have to make sure they will be filled and used while prerendering these children.
