### ISSUE TITLE
HTML Rendering 

### ISSUE THREAD

**Issue by kaystrobach** [typo3-themes/themes_gridelements#25]
When you take a "Container", "Row" and a "Horizontal Column" Grid it renders the wrong code. Single Column did it right ;-) Only <div class="col-md-xxxx"></div>

This is the code:

<div id="c34" class="csc-default  HIER MÜSSTE JA CONTAINER-FLUID STEHEN“>   100% mach er aber trotzdem
	
		<div id="c38" class="csc-default  row“>    <-  Korrekt
	
		<div id="c39" class="csc-default col-md-12"><div class="row"><div class="col-md-12 col-sm-12 col-xs-12“>   <- DAS HIER IST FALSCH Es wird hier nochmal eine row innerhalb der col-md-12 mit noch einer col-md-12 angelegt. Das ist doof, weil man dann automatisch links und rechts nochmal jeweils 15px padding hat. Schon ist keine Bündigkeit mehr in der Seite zu erreichen.
	
		<div id="c40" class="csc-default">
		
			<div class="csc-header csc-header-n1"><h1 class="csc-firstHeader">Performance-<br><strong>Manufaktur</strong></h1></div>
		
			</div>
	
		</div></div></div>
	
		</div>
	
		</div>

Can you put back the Single Column?

**Comment by kaystrobach** [comment]
@evilknevil10 this is the followup for #24

**Comment by Bunnyfield** [comment]
The second row is correct in this case, since we have to enforce the horizontal rendering - thus we have to make sure that the surrounding column will get the necessary classes, while the horizontal positioning is taken over by another row, which then contains the elements side by side.

There still is a bug though, since the elements inside that second column don't get the correct column classes, when there is no specific behaviour selected.
